//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessModel
    {
        public int Id { get; set; }
        public string ProcessModel1 { get; set; }
        public string PublishingVersion { get; set; }
    }
}
