//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromoveoDBEntities : DbContext
    {
        public PromoveoDBEntities()
            : base("name=PromoveoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ProcessModel> ProcessModels { get; set; }
        public DbSet<ProcessModel_PublishingPlatformRole> ProcessModel_PublishingPlatformRole { get; set; }
        public DbSet<PublishingPlatformRole> PublishingPlatformRoles { get; set; }
        public DbSet<PublishingPlatformUser> PublishingPlatformUsers { get; set; }
        public DbSet<PublishingPlatformUser_PublishingPlatformRole> PublishingPlatformUser_PublishingPlatformRole { get; set; }
    }
}
