//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishingPlatformUser_PublishingPlatformRole
    {
        public int Id { get; set; }
        public int FK_PublishingPlatformRole { get; set; }
        public int FK_PublishingPlatformUser { get; set; }
    
        public virtual PublishingPlatformRole PublishingPlatformRole { get; set; }
        public virtual PublishingPlatformUser PublishingPlatformUser { get; set; }
    }
}
