//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishingPlatformRole
    {
        public PublishingPlatformRole()
        {
            this.ProcessModel_PublishingPlatformRole = new HashSet<ProcessModel_PublishingPlatformRole>();
            this.PublishingPlatformUser_PublishingPlatformRole = new HashSet<PublishingPlatformUser_PublishingPlatformRole>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<ProcessModel_PublishingPlatformRole> ProcessModel_PublishingPlatformRole { get; set; }
        public virtual ICollection<PublishingPlatformUser_PublishingPlatformRole> PublishingPlatformUser_PublishingPlatformRole { get; set; }
    }
}
