//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin.PublishingPlatformRoleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_ConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_Configuration {
            get {
                return this.FK_ConfigurationField;
            }
            set {
                if ((this.FK_ConfigurationField.Equals(value) != true)) {
                    this.FK_ConfigurationField = value;
                    this.RaisePropertyChanged("FK_Configuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublishingPlatformRoleService.IPublishingPlatformRole")]
    public interface IPublishingPlatformRole {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublishingPlatformRole/CreateRole", ReplyAction="http://tempuri.org/IPublishingPlatformRole/CreateRoleResponse")]
        int CreateRole(PromoveoAddin.PublishingPlatformRoleService.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublishingPlatformRole/GetRole", ReplyAction="http://tempuri.org/IPublishingPlatformRole/GetRoleResponse")]
        PromoveoAddin.PublishingPlatformRoleService.Role GetRole(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublishingPlatformRole/GetRoles", ReplyAction="http://tempuri.org/IPublishingPlatformRole/GetRolesResponse")]
        PromoveoAddin.PublishingPlatformRoleService.Role[] GetRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublishingPlatformRole/UpdateRole", ReplyAction="http://tempuri.org/IPublishingPlatformRole/UpdateRoleResponse")]
        void UpdateRole(PromoveoAddin.PublishingPlatformRoleService.Role role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublishingPlatformRoleChannel : PromoveoAddin.PublishingPlatformRoleService.IPublishingPlatformRole, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublishingPlatformRoleClient : System.ServiceModel.ClientBase<PromoveoAddin.PublishingPlatformRoleService.IPublishingPlatformRole>, PromoveoAddin.PublishingPlatformRoleService.IPublishingPlatformRole {
        
        public PublishingPlatformRoleClient() {
        }
        
        public PublishingPlatformRoleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublishingPlatformRoleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishingPlatformRoleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishingPlatformRoleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateRole(PromoveoAddin.PublishingPlatformRoleService.Role role) {
            return base.Channel.CreateRole(role);
        }
        
        public PromoveoAddin.PublishingPlatformRoleService.Role GetRole(int Id) {
            return base.Channel.GetRole(Id);
        }
        
        public PromoveoAddin.PublishingPlatformRoleService.Role[] GetRoles() {
            return base.Channel.GetRoles();
        }
        
        public void UpdateRole(PromoveoAddin.PublishingPlatformRoleService.Role role) {
            base.Channel.UpdateRole(role);
        }
    }
}
