//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin.ModelUserRolesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shortname {
            get {
                return this.ShortnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortnameField, value) != true)) {
                    this.ShortnameField = value;
                    this.RaisePropertyChanged("Shortname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_ConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_Configuration {
            get {
                return this.FK_ConfigurationField;
            }
            set {
                if ((this.FK_ConfigurationField.Equals(value) != true)) {
                    this.FK_ConfigurationField = value;
                    this.RaisePropertyChanged("FK_Configuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelUserRolesService.IModelUserRoles")]
    public interface IModelUserRoles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelUserRoles/AssignUser", ReplyAction="http://tempuri.org/IModelUserRoles/AssignUserResponse")]
        void AssignUser(int configurationID, int modelRoleID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelUserRoles/GetAssignedUser", ReplyAction="http://tempuri.org/IModelUserRoles/GetAssignedUserResponse")]
        PromoveoAddin.ModelUserRolesService.User[] GetAssignedUser(int modelRoleID, int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelUserRoles/GetAvailableUser", ReplyAction="http://tempuri.org/IModelUserRoles/GetAvailableUserResponse")]
        PromoveoAddin.ModelUserRolesService.User[] GetAvailableUser(int modelRoleID, int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelUserRoles/GetModelUserRoles", ReplyAction="http://tempuri.org/IModelUserRoles/GetModelUserRolesResponse")]
        PromoveoAddin.ModelUserRolesService.Role[] GetModelUserRoles(int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelUserRoles/RemoveUser", ReplyAction="http://tempuri.org/IModelUserRoles/RemoveUserResponse")]
        void RemoveUser(int configurationID, int modelRoleID, int userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelUserRolesChannel : PromoveoAddin.ModelUserRolesService.IModelUserRoles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelUserRolesClient : System.ServiceModel.ClientBase<PromoveoAddin.ModelUserRolesService.IModelUserRoles>, PromoveoAddin.ModelUserRolesService.IModelUserRoles {
        
        public ModelUserRolesClient() {
        }
        
        public ModelUserRolesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelUserRolesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelUserRolesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelUserRolesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AssignUser(int configurationID, int modelRoleID, int userID) {
            base.Channel.AssignUser(configurationID, modelRoleID, userID);
        }
        
        public PromoveoAddin.ModelUserRolesService.User[] GetAssignedUser(int modelRoleID, int configurationID) {
            return base.Channel.GetAssignedUser(modelRoleID, configurationID);
        }
        
        public PromoveoAddin.ModelUserRolesService.User[] GetAvailableUser(int modelRoleID, int configurationID) {
            return base.Channel.GetAvailableUser(modelRoleID, configurationID);
        }
        
        public PromoveoAddin.ModelUserRolesService.Role[] GetModelUserRoles(int configurationID) {
            return base.Channel.GetModelUserRoles(configurationID);
        }
        
        public void RemoveUser(int configurationID, int modelRoleID, int userID) {
            base.Channel.RemoveUser(configurationID, modelRoleID, userID);
        }
    }
}
