//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6387
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ServiceModel;

namespace ServiceClient
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", ConfigurationName = "WorkflowSoap")]
    public interface WorkflowSoap
    {

        // CODEGEN: Generating message contract since element name item from namespace http://schemas.microsoft.com/sharepoint/soap/workflow/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.microsoft.com/sharepoint/soap/workflow/GetToDosForItem", ReplyAction = "*")]
        GetToDosForItemResponse GetToDosForItem(GetToDosForItemRequest request);

        // CODEGEN: Generating message contract since element name item from namespace http://schemas.microsoft.com/sharepoint/soap/workflow/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.microsoft.com/sharepoint/soap/workflow/GetTemplatesForItem", ReplyAction = "*")]
        GetTemplatesForItemResponse GetTemplatesForItem(GetTemplatesForItemRequest request);

        // CODEGEN: Generating message contract since element name item from namespace http://schemas.microsoft.com/sharepoint/soap/workflow/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.microsoft.com/sharepoint/soap/workflow/StartWorkflow", ReplyAction = "*")]
        StartWorkflowResponse StartWorkflow(StartWorkflowRequest request);

        // CODEGEN: Generating message contract since element name item from namespace http://schemas.microsoft.com/sharepoint/soap/workflow/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.microsoft.com/sharepoint/soap/workflow/AlterToDo", ReplyAction = "*")]
        AlterToDoResponse AlterToDo(AlterToDoRequest request);

        // CODEGEN: Generating message contract since element name item from namespace http://schemas.microsoft.com/sharepoint/soap/workflow/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.microsoft.com/sharepoint/soap/workflow/GetWorkflowDataForItem", ReplyAction = "*")]
        GetWorkflowDataForItemResponse GetWorkflowDataForItem(GetWorkflowDataForItemRequest request);

        // CODEGEN: Generating message contract since element name item from namespace http://schemas.microsoft.com/sharepoint/soap/workflow/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.microsoft.com/sharepoint/soap/workflow/ClaimReleaseTask", ReplyAction = "*")]
        ClaimReleaseTaskResponse ClaimReleaseTask(ClaimReleaseTaskRequest request);

        // CODEGEN: Generating message contract since element name item from namespace http://schemas.microsoft.com/sharepoint/soap/workflow/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.microsoft.com/sharepoint/soap/workflow/GetWorkflowTaskData", ReplyAction = "*")]
        GetWorkflowTaskDataResponse GetWorkflowTaskData(GetWorkflowTaskDataRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetToDosForItemRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetToDosForItem", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public GetToDosForItemRequestBody Body;

        public GetToDosForItemRequest()
        {
        }

        public GetToDosForItemRequest(GetToDosForItemRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class GetToDosForItemRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string item;

        public GetToDosForItemRequestBody()
        {
        }

        public GetToDosForItemRequestBody(string item)
        {
            this.item = item;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetToDosForItemResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetToDosForItemResponse", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public GetToDosForItemResponseBody Body;

        public GetToDosForItemResponse()
        {
        }

        public GetToDosForItemResponse(GetToDosForItemResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class GetToDosForItemResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement GetToDosForItemResult;

        public GetToDosForItemResponseBody()
        {
        }

        public GetToDosForItemResponseBody(System.Xml.XmlElement GetToDosForItemResult)
        {
            this.GetToDosForItemResult = GetToDosForItemResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetTemplatesForItemRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetTemplatesForItem", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public GetTemplatesForItemRequestBody Body;

        public GetTemplatesForItemRequest()
        {
        }

        public GetTemplatesForItemRequest(GetTemplatesForItemRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class GetTemplatesForItemRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string item;

        public GetTemplatesForItemRequestBody()
        {
        }

        public GetTemplatesForItemRequestBody(string item)
        {
            this.item = item;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetTemplatesForItemResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetTemplatesForItemResponse", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public GetTemplatesForItemResponseBody Body;

        public GetTemplatesForItemResponse()
        {
        }

        public GetTemplatesForItemResponse(GetTemplatesForItemResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class GetTemplatesForItemResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement GetTemplatesForItemResult;

        public GetTemplatesForItemResponseBody()
        {
        }

        public GetTemplatesForItemResponseBody(System.Xml.XmlElement GetTemplatesForItemResult)
        {
            this.GetTemplatesForItemResult = GetTemplatesForItemResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class StartWorkflowRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "StartWorkflow", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public StartWorkflowRequestBody Body;

        public StartWorkflowRequest()
        {
        }

        public StartWorkflowRequest(StartWorkflowRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class StartWorkflowRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string item;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid templateId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public System.Xml.XmlElement workflowParameters;

        public StartWorkflowRequestBody()
        {
        }

        public StartWorkflowRequestBody(string item, System.Guid templateId, System.Xml.XmlElement workflowParameters)
        {
            this.item = item;
            this.templateId = templateId;
            this.workflowParameters = workflowParameters;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    [XmlSerializerFormat]
    [ServiceContract] 
    public partial class StartWorkflowResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "StartWorkflowResponse", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public StartWorkflowResponseBody Body;

        public StartWorkflowResponse()
        {
        }

        public StartWorkflowResponse(StartWorkflowResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class StartWorkflowResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement StartWorkflowResult { get; set; }

        public StartWorkflowResponseBody()
        {
        }

        public StartWorkflowResponseBody(System.Xml.XmlElement StartWorkflowResult)
        {
            this.StartWorkflowResult = StartWorkflowResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class AlterToDoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "AlterToDo", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public AlterToDoRequestBody Body;

        public AlterToDoRequest()
        {
        }

        public AlterToDoRequest(AlterToDoRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class AlterToDoRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string item;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int todoId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.Guid todoListId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public System.Xml.XmlElement taskData;

        public AlterToDoRequestBody()
        {
        }

        public AlterToDoRequestBody(string item, int todoId, System.Guid todoListId, System.Xml.XmlElement taskData)
        {
            this.item = item;
            this.todoId = todoId;
            this.todoListId = todoListId;
            this.taskData = taskData;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class AlterToDoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "AlterToDoResponse", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public AlterToDoResponseBody Body;

        public AlterToDoResponse()
        {
        }

        public AlterToDoResponse(AlterToDoResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class AlterToDoResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement AlterToDoResult;

        public AlterToDoResponseBody()
        {
        }

        public AlterToDoResponseBody(System.Xml.XmlElement AlterToDoResult)
        {
            this.AlterToDoResult = AlterToDoResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetWorkflowDataForItemRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetWorkflowDataForItem", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public GetWorkflowDataForItemRequestBody Body;

        public GetWorkflowDataForItemRequest()
        {
        }

        public GetWorkflowDataForItemRequest(GetWorkflowDataForItemRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class GetWorkflowDataForItemRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string item;

        public GetWorkflowDataForItemRequestBody()
        {
        }

        public GetWorkflowDataForItemRequestBody(string item)
        {
            this.item = item;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetWorkflowDataForItemResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetWorkflowDataForItemResponse", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public GetWorkflowDataForItemResponseBody Body;

        public GetWorkflowDataForItemResponse()
        {
        }

        public GetWorkflowDataForItemResponse(GetWorkflowDataForItemResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class GetWorkflowDataForItemResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement GetWorkflowDataForItemResult;

        public GetWorkflowDataForItemResponseBody()
        {
        }

        public GetWorkflowDataForItemResponseBody(System.Xml.XmlElement GetWorkflowDataForItemResult)
        {
            this.GetWorkflowDataForItemResult = GetWorkflowDataForItemResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ClaimReleaseTaskRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ClaimReleaseTask", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public ClaimReleaseTaskRequestBody Body;

        public ClaimReleaseTaskRequest()
        {
        }

        public ClaimReleaseTaskRequest(ClaimReleaseTaskRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class ClaimReleaseTaskRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string item;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int taskId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.Guid listId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public bool fClaim;

        public ClaimReleaseTaskRequestBody()
        {
        }

        public ClaimReleaseTaskRequestBody(string item, int taskId, System.Guid listId, bool fClaim)
        {
            this.item = item;
            this.taskId = taskId;
            this.listId = listId;
            this.fClaim = fClaim;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ClaimReleaseTaskResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ClaimReleaseTaskResponse", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public ClaimReleaseTaskResponseBody Body;

        public ClaimReleaseTaskResponse()
        {
        }

        public ClaimReleaseTaskResponse(ClaimReleaseTaskResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class ClaimReleaseTaskResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement ClaimReleaseTaskResult;

        public ClaimReleaseTaskResponseBody()
        {
        }

        public ClaimReleaseTaskResponseBody(System.Xml.XmlElement ClaimReleaseTaskResult)
        {
            this.ClaimReleaseTaskResult = ClaimReleaseTaskResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetWorkflowTaskDataRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetWorkflowTaskData", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public GetWorkflowTaskDataRequestBody Body;

        public GetWorkflowTaskDataRequest()
        {
        }

        public GetWorkflowTaskDataRequest(GetWorkflowTaskDataRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class GetWorkflowTaskDataRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string item;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int taskId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.Guid listId;

        public GetWorkflowTaskDataRequestBody()
        {
        }

        public GetWorkflowTaskDataRequestBody(string item, int taskId, System.Guid listId)
        {
            this.item = item;
            this.taskId = taskId;
            this.listId = listId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetWorkflowTaskDataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetWorkflowTaskDataResponse", Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/", Order = 0)]
        public GetWorkflowTaskDataResponseBody Body;

        public GetWorkflowTaskDataResponse()
        {
        }

        public GetWorkflowTaskDataResponse(GetWorkflowTaskDataResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://schemas.microsoft.com/sharepoint/soap/workflow/")]
    public partial class GetWorkflowTaskDataResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement GetWorkflowTaskDataResult;

        public GetWorkflowTaskDataResponseBody()
        {
        }

        public GetWorkflowTaskDataResponseBody(System.Xml.XmlElement GetWorkflowTaskDataResult)
        {
            this.GetWorkflowTaskDataResult = GetWorkflowTaskDataResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WorkflowSoapChannel : WorkflowSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WorkflowSoapClient : System.ServiceModel.ClientBase<WorkflowSoap>, WorkflowSoap
    {

        public WorkflowSoapClient()
        {
        }

        public WorkflowSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public WorkflowSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WorkflowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WorkflowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetToDosForItemResponse WorkflowSoap.GetToDosForItem(GetToDosForItemRequest request)
        {
            return base.Channel.GetToDosForItem(request);
        }

        public System.Xml.XmlElement GetToDosForItem(string item)
        {
            GetToDosForItemRequest inValue = new GetToDosForItemRequest();
            inValue.Body = new GetToDosForItemRequestBody();
            inValue.Body.item = item;
            GetToDosForItemResponse retVal = ((WorkflowSoap)(this)).GetToDosForItem(inValue);
            return retVal.Body.GetToDosForItemResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetTemplatesForItemResponse WorkflowSoap.GetTemplatesForItem(GetTemplatesForItemRequest request)
        {
            return base.Channel.GetTemplatesForItem(request);
        }

        public System.Xml.XmlElement GetTemplatesForItem(string item)
        {
            GetTemplatesForItemRequest inValue = new GetTemplatesForItemRequest();
            inValue.Body = new GetTemplatesForItemRequestBody();
            inValue.Body.item = item;
            GetTemplatesForItemResponse retVal = ((WorkflowSoap)(this)).GetTemplatesForItem(inValue);
            return retVal.Body.GetTemplatesForItemResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StartWorkflowResponse WorkflowSoap.StartWorkflow(StartWorkflowRequest request)
        {
            return base.Channel.StartWorkflow(request);
        }

        public System.Xml.XmlElement StartWorkflow(string item, System.Guid templateId, System.Xml.XmlElement workflowParameters)
        {
            StartWorkflowRequest inValue = new StartWorkflowRequest();
            inValue.Body = new StartWorkflowRequestBody();
            inValue.Body.item = item;
            inValue.Body.templateId = templateId;
            inValue.Body.workflowParameters = workflowParameters;
            StartWorkflowResponse retVal = ((WorkflowSoap)(this)).StartWorkflow(inValue);
            return retVal.Body.StartWorkflowResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AlterToDoResponse WorkflowSoap.AlterToDo(AlterToDoRequest request)
        {
            return base.Channel.AlterToDo(request);
        }

        public System.Xml.XmlElement AlterToDo(string item, int todoId, System.Guid todoListId, System.Xml.XmlElement taskData)
        {
            AlterToDoRequest inValue = new AlterToDoRequest();
            inValue.Body = new AlterToDoRequestBody();
            inValue.Body.item = item;
            inValue.Body.todoId = todoId;
            inValue.Body.todoListId = todoListId;
            inValue.Body.taskData = taskData;
            AlterToDoResponse retVal = ((WorkflowSoap)(this)).AlterToDo(inValue);
            return retVal.Body.AlterToDoResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetWorkflowDataForItemResponse WorkflowSoap.GetWorkflowDataForItem(GetWorkflowDataForItemRequest request)
        {
            return base.Channel.GetWorkflowDataForItem(request);
        }

        public System.Xml.XmlElement GetWorkflowDataForItem(string item)
        {
            GetWorkflowDataForItemRequest inValue = new GetWorkflowDataForItemRequest();
            inValue.Body = new GetWorkflowDataForItemRequestBody();
            inValue.Body.item = item;
            GetWorkflowDataForItemResponse retVal = ((WorkflowSoap)(this)).GetWorkflowDataForItem(inValue);
            return retVal.Body.GetWorkflowDataForItemResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClaimReleaseTaskResponse WorkflowSoap.ClaimReleaseTask(ClaimReleaseTaskRequest request)
        {
            return base.Channel.ClaimReleaseTask(request);
        }

        public System.Xml.XmlElement ClaimReleaseTask(string item, int taskId, System.Guid listId, bool fClaim)
        {
            ClaimReleaseTaskRequest inValue = new ClaimReleaseTaskRequest();
            inValue.Body = new ClaimReleaseTaskRequestBody();
            inValue.Body.item = item;
            inValue.Body.taskId = taskId;
            inValue.Body.listId = listId;
            inValue.Body.fClaim = fClaim;
            ClaimReleaseTaskResponse retVal = ((WorkflowSoap)(this)).ClaimReleaseTask(inValue);
            return retVal.Body.ClaimReleaseTaskResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetWorkflowTaskDataResponse WorkflowSoap.GetWorkflowTaskData(GetWorkflowTaskDataRequest request)
        {
            return base.Channel.GetWorkflowTaskData(request);
        }

        public System.Xml.XmlElement GetWorkflowTaskData(string item, int taskId, System.Guid listId)
        {
            GetWorkflowTaskDataRequest inValue = new GetWorkflowTaskDataRequest();
            inValue.Body = new GetWorkflowTaskDataRequestBody();
            inValue.Body.item = item;
            inValue.Body.taskId = taskId;
            inValue.Body.listId = listId;
            GetWorkflowTaskDataResponse retVal = ((WorkflowSoap)(this)).GetWorkflowTaskData(inValue);
            return retVal.Body.GetWorkflowTaskDataResult;
        }
    }
}