//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin.ProcessModelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessModel", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class ProcessModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcknowledgeStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_ConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_PublishingPlatformUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcknowledgeState {
            get {
                return this.AcknowledgeStateField;
            }
            set {
                if ((object.ReferenceEquals(this.AcknowledgeStateField, value) != true)) {
                    this.AcknowledgeStateField = value;
                    this.RaisePropertyChanged("AcknowledgeState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_Configuration {
            get {
                return this.FK_ConfigurationField;
            }
            set {
                if ((this.FK_ConfigurationField.Equals(value) != true)) {
                    this.FK_ConfigurationField = value;
                    this.RaisePropertyChanged("FK_Configuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_PublishingPlatformUser {
            get {
                return this.FK_PublishingPlatformUserField;
            }
            set {
                if ((this.FK_PublishingPlatformUserField.Equals(value) != true)) {
                    this.FK_PublishingPlatformUserField = value;
                    this.RaisePropertyChanged("FK_PublishingPlatformUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shortname {
            get {
                return this.ShortnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortnameField, value) != true)) {
                    this.ShortnameField = value;
                    this.RaisePropertyChanged("Shortname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgeState", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary")]
    public enum AcknowledgeState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Merged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MergedAndPublished = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Acknowledged = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcessModelService.IProcessModel")]
    public interface IProcessModel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/AddNewModels", ReplyAction="http://tempuri.org/IProcessModel/AddNewModelsResponse")]
        void AddNewModels(string[] modelNames, int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/CreateVersion", ReplyAction="http://tempuri.org/IProcessModel/CreateVersionResponse")]
        void CreateVersion(string modelName, int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/GetModelID", ReplyAction="http://tempuri.org/IProcessModel/GetModelIDResponse")]
        int GetModelID(string processModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/GetProcessModels", ReplyAction="http://tempuri.org/IProcessModel/GetProcessModelsResponse")]
        PromoveoAddin.ProcessModelService.ProcessModel[] GetProcessModels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/GetProcessModelsByConfigID", ReplyAction="http://tempuri.org/IProcessModel/GetProcessModelsByConfigIDResponse")]
        PromoveoAddin.ProcessModelService.ProcessModel[] GetProcessModelsByConfigID(int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/GetUsers", ReplyAction="http://tempuri.org/IProcessModel/GetUsersResponse")]
        PromoveoAddin.ProcessModelService.User[] GetUsers(string processModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/GetNewModelNames", ReplyAction="http://tempuri.org/IProcessModel/GetNewModelNamesResponse")]
        string[] GetNewModelNames(string[] modelNames, int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/Insert", ReplyAction="http://tempuri.org/IProcessModel/InsertResponse")]
        void Insert(string modelName, int configID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/IsModelOfConfiguration", ReplyAction="http://tempuri.org/IProcessModel/IsModelOfConfigurationResponse")]
        bool IsModelOfConfiguration(string modelName, int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessModel/SetAcknowledgeState", ReplyAction="http://tempuri.org/IProcessModel/SetAcknowledgeStateResponse")]
        void SetAcknowledgeState(int configurationID, string modelName, PromoveoAddin.ProcessModelService.AcknowledgeState state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessModelChannel : PromoveoAddin.ProcessModelService.IProcessModel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessModelClient : System.ServiceModel.ClientBase<PromoveoAddin.ProcessModelService.IProcessModel>, PromoveoAddin.ProcessModelService.IProcessModel {
        
        public ProcessModelClient() {
        }
        
        public ProcessModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNewModels(string[] modelNames, int configurationID) {
            base.Channel.AddNewModels(modelNames, configurationID);
        }
        
        public void CreateVersion(string modelName, int configurationID) {
            base.Channel.CreateVersion(modelName, configurationID);
        }
        
        public int GetModelID(string processModel) {
            return base.Channel.GetModelID(processModel);
        }
        
        public PromoveoAddin.ProcessModelService.ProcessModel[] GetProcessModels() {
            return base.Channel.GetProcessModels();
        }
        
        public PromoveoAddin.ProcessModelService.ProcessModel[] GetProcessModelsByConfigID(int configurationID) {
            return base.Channel.GetProcessModelsByConfigID(configurationID);
        }
        
        public PromoveoAddin.ProcessModelService.User[] GetUsers(string processModel) {
            return base.Channel.GetUsers(processModel);
        }
        
        public string[] GetNewModelNames(string[] modelNames, int configurationID) {
            return base.Channel.GetNewModelNames(modelNames, configurationID);
        }
        
        public void Insert(string modelName, int configID) {
            base.Channel.Insert(modelName, configID);
        }
        
        public bool IsModelOfConfiguration(string modelName, int configurationID) {
            return base.Channel.IsModelOfConfiguration(modelName, configurationID);
        }
        
        public void SetAcknowledgeState(int configurationID, string modelName, PromoveoAddin.ProcessModelService.AcknowledgeState state) {
            base.Channel.SetAcknowledgeState(configurationID, modelName, state);
        }
    }
}
