//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin.ModelToPublishingPlatformRoleAssignmentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelToPublishingPlatformRoleAssignment", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class ModelToPublishingPlatformRoleAssignment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_ProcessModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_PublishingPlatformRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_ProcessModel {
            get {
                return this.FK_ProcessModelField;
            }
            set {
                if ((this.FK_ProcessModelField.Equals(value) != true)) {
                    this.FK_ProcessModelField = value;
                    this.RaisePropertyChanged("FK_ProcessModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_PublishingPlatformRole {
            get {
                return this.FK_PublishingPlatformRoleField;
            }
            set {
                if ((this.FK_PublishingPlatformRoleField.Equals(value) != true)) {
                    this.FK_PublishingPlatformRoleField = value;
                    this.RaisePropertyChanged("FK_PublishingPlatformRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelToPublishingPlatformRoleAssignmentService.IModelToPublishingPlatformRoleAssi" +
        "gnment")]
    public interface IModelToPublishingPlatformRoleAssignment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelToPublishingPlatformRoleAssignment/GetModelsOfRole", ReplyAction="http://tempuri.org/IModelToPublishingPlatformRoleAssignment/GetModelsOfRoleRespon" +
            "se")]
        PromoveoAddin.ModelToPublishingPlatformRoleAssignmentService.ModelToPublishingPlatformRoleAssignment[] GetModelsOfRole(int RoleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelToPublishingPlatformRoleAssignment/IsChecked", ReplyAction="http://tempuri.org/IModelToPublishingPlatformRoleAssignment/IsCheckedResponse")]
        bool IsChecked(string Model, int RoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelToPublishingPlatformRoleAssignment/PersistRoleModelAssig" +
            "nment", ReplyAction="http://tempuri.org/IModelToPublishingPlatformRoleAssignment/PersistRoleModelAssig" +
            "nmentResponse")]
        void PersistRoleModelAssignment(string Model, int RoleID, bool isChecked);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelToPublishingPlatformRoleAssignmentChannel : PromoveoAddin.ModelToPublishingPlatformRoleAssignmentService.IModelToPublishingPlatformRoleAssignment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelToPublishingPlatformRoleAssignmentClient : System.ServiceModel.ClientBase<PromoveoAddin.ModelToPublishingPlatformRoleAssignmentService.IModelToPublishingPlatformRoleAssignment>, PromoveoAddin.ModelToPublishingPlatformRoleAssignmentService.IModelToPublishingPlatformRoleAssignment {
        
        public ModelToPublishingPlatformRoleAssignmentClient() {
        }
        
        public ModelToPublishingPlatformRoleAssignmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelToPublishingPlatformRoleAssignmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelToPublishingPlatformRoleAssignmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelToPublishingPlatformRoleAssignmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PromoveoAddin.ModelToPublishingPlatformRoleAssignmentService.ModelToPublishingPlatformRoleAssignment[] GetModelsOfRole(int RoleId) {
            return base.Channel.GetModelsOfRole(RoleId);
        }
        
        public bool IsChecked(string Model, int RoleID) {
            return base.Channel.IsChecked(Model, RoleID);
        }
        
        public void PersistRoleModelAssignment(string Model, int RoleID, bool isChecked) {
            base.Channel.PersistRoleModelAssignment(Model, RoleID, isChecked);
        }
    }
}
