//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin.UserRoleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shortname {
            get {
                return this.ShortnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortnameField, value) != true)) {
                    this.ShortnameField = value;
                    this.RaisePropertyChanged("Shortname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserRoleService.IUserRole")]
    public interface IUserRole {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRole/AssignUser", ReplyAction="http://tempuri.org/IUserRole/AssignUserResponse")]
        void AssignUser(int roleID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRole/GetAssignedUsers", ReplyAction="http://tempuri.org/IUserRole/GetAssignedUsersResponse")]
        PromoveoAddin.UserRoleService.User[] GetAssignedUsers(int roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRole/GetUnassignedUsers", ReplyAction="http://tempuri.org/IUserRole/GetUnassignedUsersResponse")]
        PromoveoAddin.UserRoleService.User[] GetUnassignedUsers(int roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRole/RemoveUser", ReplyAction="http://tempuri.org/IUserRole/RemoveUserResponse")]
        void RemoveUser(int roleID, int userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserRoleChannel : PromoveoAddin.UserRoleService.IUserRole, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRoleClient : System.ServiceModel.ClientBase<PromoveoAddin.UserRoleService.IUserRole>, PromoveoAddin.UserRoleService.IUserRole {
        
        public UserRoleClient() {
        }
        
        public UserRoleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserRoleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRoleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRoleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AssignUser(int roleID, int userID) {
            base.Channel.AssignUser(roleID, userID);
        }
        
        public PromoveoAddin.UserRoleService.User[] GetAssignedUsers(int roleID) {
            return base.Channel.GetAssignedUsers(roleID);
        }
        
        public PromoveoAddin.UserRoleService.User[] GetUnassignedUsers(int roleID) {
            return base.Channel.GetUnassignedUsers(roleID);
        }
        
        public void RemoveUser(int roleID, int userID) {
            base.Channel.RemoveUser(roleID, userID);
        }
    }
}
