//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoveoAddin.ConfigurationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Configuration", Namespace="http://schemas.datacontract.org/2004/07/PromoveoServiceLibrary.DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Configuration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisioMasterFilenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisioMasterFilename {
            get {
                return this.VisioMasterFilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.VisioMasterFilenameField, value) != true)) {
                    this.VisioMasterFilenameField = value;
                    this.RaisePropertyChanged("VisioMasterFilename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationService.IConfiguration")]
    public interface IConfiguration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/GetVisioMasterFileName", ReplyAction="http://tempuri.org/IConfiguration/GetVisioMasterFileNameResponse")]
        string GetVisioMasterFileName(int configurationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/SetVisioMasterFileName", ReplyAction="http://tempuri.org/IConfiguration/SetVisioMasterFileNameResponse")]
        void SetVisioMasterFileName(int configurationID, string visioMasterFilename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/GetConfigurations", ReplyAction="http://tempuri.org/IConfiguration/GetConfigurationsResponse")]
        PromoveoAddin.ConfigurationService.Configuration[] GetConfigurations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/CreateConfiguration", ReplyAction="http://tempuri.org/IConfiguration/CreateConfigurationResponse")]
        int CreateConfiguration(PromoveoAddin.ConfigurationService.Configuration configuration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/UpdateConfiguration", ReplyAction="http://tempuri.org/IConfiguration/UpdateConfigurationResponse")]
        void UpdateConfiguration(PromoveoAddin.ConfigurationService.Configuration configuration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/DeleteConfiguration", ReplyAction="http://tempuri.org/IConfiguration/DeleteConfigurationResponse")]
        void DeleteConfiguration(PromoveoAddin.ConfigurationService.Configuration configuration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigurationChannel : PromoveoAddin.ConfigurationService.IConfiguration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationClient : System.ServiceModel.ClientBase<PromoveoAddin.ConfigurationService.IConfiguration>, PromoveoAddin.ConfigurationService.IConfiguration {
        
        public ConfigurationClient() {
        }
        
        public ConfigurationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVisioMasterFileName(int configurationID) {
            return base.Channel.GetVisioMasterFileName(configurationID);
        }
        
        public void SetVisioMasterFileName(int configurationID, string visioMasterFilename) {
            base.Channel.SetVisioMasterFileName(configurationID, visioMasterFilename);
        }
        
        public PromoveoAddin.ConfigurationService.Configuration[] GetConfigurations() {
            return base.Channel.GetConfigurations();
        }
        
        public int CreateConfiguration(PromoveoAddin.ConfigurationService.Configuration configuration) {
            return base.Channel.CreateConfiguration(configuration);
        }
        
        public void UpdateConfiguration(PromoveoAddin.ConfigurationService.Configuration configuration) {
            base.Channel.UpdateConfiguration(configuration);
        }
        
        public void DeleteConfiguration(PromoveoAddin.ConfigurationService.Configuration configuration) {
            base.Channel.DeleteConfiguration(configuration);
        }
    }
}
